#!/bin/bash
set -e
umask 077

if [[ ! "$1" =~ ^[a-z0-9\-]{1,15}$ ]]; then
	echo "must provide a valid lain-wg instance name (regexp ^[a-z0-9\-]{1,15}$)" 1>&2
	exit 1
fi

netns="/etc/lain/wg/$1"; shift
mkdir -p "$netns"

# generate key
privatekey="$(mktemp)"
publickey="$(wg genkey | tee "$privatekey" | wg pubkey)"

# manual exchange
printf "public key: %s\n" "$publickey"
printf "enter interface address (cidr): "
IFS= read -r address
printf "enter server public key: "
IFS= read -r peerkey
printf "enter endpoint address (ip:port): "
IFS= read -r endpoint

# write config
systemd-creds encrypt - "$netns/interface.conf" <<EOF
[Interface]
PrivateKey = $(<"$privatekey")
EOF

systemd-creds encrypt - "$netns/peer.conf" <<EOF
[Peer]
PublicKey = $peerkey
AllowedIPs = 0.0.0.0/0
EndPoint = $endpoint
EOF

systemd-creds encrypt - "$netns/address" <<< "$address"

rm "$privatekey"
