#!/bin/bash
set -e
umask 077
if ! prefix="$(readlink -m "/etc/lain/wg/mullvad/$1")"; then
	echo 'bad prefix' 1>&2
	exit 1
fi

if ! [[ "$prefix" == '/etc/lain/wg/mullvad' || "$prefix" =~ ^/etc/lain/wg/mullvad/ ]]; then
	echo 'prefix escape' 1>&2
	exit 1
fi

# prompt for mullvad account
printf 'enter mulvad account number: '
IFS= read -rs accountNumber
printf '\n'

# retreive account authorization
account="$(mktemp)"
status="$(curl --config - <<EOF
silent
output="$account"
url="https://api.mullvad.net/www/accounts/$accountNumber/"
write-out="%{http_code}"
EOF
)"
rc=$?

if [[ "$rc" -ne 0 || "$status" -ne 200 || ! -s "$account" ]]; then
	rm "$account"
	echo 'failed to retreive account details' 1>&2
	exit 1
fi

# revoke previos key
if [[ -s "$prefix/.register/pubkey" ]]; then
	data="$(mktemp)"; jq -n '{$pubkey}' --arg pubkey "$(systemd-creds decrypt "$prefix/.register/pubkey" -)" > "$data"
	status="$(curl --config - <<EOF
silent
output="$assoc"
request="POST"
url="https://api-www.mullvad.net/www/wg-pubkeys/revoke/"
header="Content-Type: application/json"
write-out="%{http_code}"
header="Authorization: Token $(jq -r .auth_token "$account")"
data="@$data"
EOF
	)"
	rc=$?

	rm "$data"
	if [[ "$rc" -ne 0 || "$status" -ne 204 ]]; then
		rm "$account"
		echo 'failed to revoke public key' 1>&2
		exit 1
	fi
fi

# generate key
privatekey="$(mktemp)"
publickey="$(wg genkey | tee "$privatekey" | wg pubkey)"

# register key and receive associations
# note - no preshared key
assoc="$(mktemp)"
data="$(mktemp)"; jq -n '{$pubkey}' --arg pubkey "$publickey" > "$data"
status="$(curl --config - <<EOF
silent
output="$assoc"
request="POST"
url="https://api.mullvad.net/www/wg-pubkeys/add/"
header="Content-Type: application/json"
write-out="%{http_code}"
header="Authorization: Token $(jq -r .auth_token "$account")"
data="@$data"
EOF
)"
rc=$?
rm "$data"

if [[ "$rc" -ne 0 || "$status" -ne 201 || ! -s "$assoc" ]]; then
	rm "$account" "$assoc"
	echo 'failed to register public key' 1>&2
	exit 1
fi

mkdir -p "$prefix/.register"
systemd-creds encrypt - "$prefix/.register/pubkey" <<< "$publickey"
systemd-creds encrypt - "$prefix/.register/address" <<< "$(jq -r '.ipv4_address' "$assoc")"
systemd-creds encrypt - "$prefix/.register/interface.conf" << EOF
[Interface]
PrivateKey = $(<"$privatekey")
EOF

rm "$account" "$assoc" "$privatekey"

# generate configs
lain-reinit-wg-mullvad "$@"
